name: "Docs Generator"
on:
  workflow_dispatch:
    inputs:
      go_algorand_version:
        description: "Go-Algorand Version"
        type: string
        required: false
        default: 'latest'
      indexer_version:
        description: "Indexer Version"
        type: string
        required: false
        default: 'latest'

jobs:
  pr-generator:
    runs-on: ubuntu-latest
    steps:

      - name: Install dependencies
        run: |
          wget --version
          java --version
          bzip2 --version
          git --version

      - name: Clone docs repo
        uses: actions/checkout@v3
        with:
          path: docs

      - name: Clone go-algorand repo
        uses: actions/checkout@v3
        with:
          repository: algorand/go-algorand
          ref: rel/stable
          path: go-algorand

      - name: Get latest go-algorand version
        run: |
          if ${{ (inputs.go_algorand_version == 'latest') || (inputs.go_algorand_version == '') }}; then
            cd go-algorand
            git fetch --tags
            echo "Setting GO_ALGORAND_VERSION to latest:"
            git tag --list 'v[0-9]*.[0-9]*.[0-9]*-stable' | sort -V | tail -1 | sed 's/v//' | sed 's/-stable//'
            echo "GO_ALGORAND_VERSION=$(git tag --list 'v[0-9]*.[0-9]*.[0-9]*-stable' | sort -V | tail -1 | sed 's/v//' | sed 's/-stable//')" >> $GITHUB_ENV
          else
            echo "GO_ALGORAND_VERSION=${{ inputs.go_algorand_version }}" >> $GITHUB_ENV
            echo "GO_ALGORAND_VERSION set to passed value: ${{ inputs.go_algorand_version }}"
          fi

      - name: Clone Indexer repo
        uses: actions/checkout@v3
        with:
          repository: algorand/indexer
          ref: master
          path: indexer

      - name: Get latest indexer version
        run: |
          if ${{ (inputs.indexer_version == 'latest') || (inputs.indexer_version == '') }}; then
            cd indexer
            git fetch --tags
            echo "Setting INDEXER_VERSION to latest:"
            git tag --list '[0-9]*.[0-9]*.[0-9]*' | grep -v "-" | sort -V | tail -1
            echo "INDEXER_VERSION=$(git tag --list '[0-9]*.[0-9]*.[0-9]*' | grep -v "-" | sort -V | tail -1)" >> $GITHUB_ENV
          else
            echo "INDEXER_VERSION=${{ inputs.indexer_version }}" >> $GITHUB_ENV
            echo "INDEXER_VERSION set to passed value: ${{ inputs.indexer_version }}"
          fi

      - name: Download binaries
        run: |
          wget https://algorand-releases.s3.amazonaws.com/channel/stable/node_stable_linux-amd64_${{ env.GO_ALGORAND_VERSION }}.tar.gz
          wget https://algorand-releases.s3.amazonaws.com/indexer/${{ env.INDEXER_VERSION }}/algorand-indexer_linux_amd64_${{ env.INDEXER_VERSION }}.tar.bz2
          ls -la

      - name: Install binaries
        run: |
          mkdir -p ~/go/bin
          mkdir -p node_stable_linux-amd64_${{ env.GO_ALGORAND_VERSION }}
          tar xzf node_stable_linux-amd64_${{ env.GO_ALGORAND_VERSION }}.tar.gz -C node_stable_linux-amd64_${{ env.GO_ALGORAND_VERSION }}/
          cd node_stable_linux-amd64_${{ env.GO_ALGORAND_VERSION }}/bin/
          cp goal algokey kmd diagcfg tealdbg  ~/go/bin/
          cd ../../
          tar xjf algorand-indexer_linux_amd64_${{ env.INDEXER_VERSION }}.tar.bz2
          cp algorand-indexer_linux_amd64_${{ env.INDEXER_VERSION }}/algorand-indexer ~/go/bin/
          ls -la
          ls -la ~/go/bin

      - name: Run doc generator
        run: |
          cd docs/scripts/
          ./reformat-all-commands.sh ../../go-algorand/ ../../indexer/
          git diff

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          path: docs
          branch: "automatic-pr-go-algorand-${{ env.GO_ALGORAND_VERSION }}-indexer-${{ env.INDEXER_VERSION }}"
          title: "Automatic PR for go-algorand: ${{ env.GO_ALGORAND_VERSION }} and indexer: ${{ env.INDEXER_VERSION }}"
          body: "Changes generated by reformat-all-commands.sh script automatically."
          reviewers: "nullun,barnjamin,ryanrfox"
          delete-branch: true
          base: staging
