name: "PR Generator"
on:
  workflow_dispatch:
    inputs:
      go-algorand-version:
        description: "Go-Algorand Version"
        type: string
        required: false
        default: 'latest'
      indexer-version:
        description: "Indexer Version"
        type: string
        required: false
        default: 'latest'
jobs:
  pr-generator:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: |
          wget --version
          java --version
          bzip --version
          git --version
      - name: Clone go-algorand
      - name: Clone Indexer
      - name: Download binaries
      - name: Install binaries
      - name: Run doc generator
      - name: Create PR
