name: "PR Generator"
on:
  workflow_dispatch:
    inputs:
      go-algorand-version:
        description: "Go-Algorand Version"
        type: string
        required: false
        default: 'latest' # TODO
      indexer-version:
        description: "Indexer Version"
        type: string
        required: false
        default: 'latest' # TODO
  push: # Temporary for testing
jobs:
  pr-generator:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: |
          wget --version
          java --version
          bzip2 --version
          git --version
      - name: Clone docs repo
        uses: actions/checkout@v3
        with:
          path: docs
      - name: Clone go-algorand repo
        uses: actions/checkout@v3
        with:
          repository: algorand/go-algorand
          ref: rel/stable
          path: go-algorand
      - name: Clone Indexer repo
        uses: actions/checkout@v3
        with:
          repository: algorand/indexer
          ref: master
          path: indexer
      - name: Download binaries
        run: |
          cd ../../
          # TODO: use passed version or latest
          wget https://algorand-releases.s3.amazonaws.com/channel/stable/node_stable_linux-amd64_3.8.1.tar.gz
          wget https://algorand-releases.s3.amazonaws.com/indexer/2.13.0/algorand-indexer_linux_amd64_2.13.0.tar.bz2
          ls -la
      - name: Install binaries
        run: |
          # TODO: use passed version or latest
          cd ../../
          mkdir -p ~/go/bin
          mkdir -p node_stable_linux-amd64_3.8.1
          tar xzf node_stable_linux-amd64_3.8.1.tar.gz -C node_stable_linux-amd64_3.8.1/
          cd node_stable_linux-amd64_3.8.1/bin/
          cp goal algokey kmd diagcfg tealdbg  ~/go/bin/
          cd ../../
          tar xjf algorand-indexer_linux_amd64_2.13.0.tar.bz2
          cp algorand-indexer_linux_amd64_2.13.0/algorand-indexer ~/go/bin/
          ls -la
          ls -la ~/go/bin
      - name: Run doc generator
        run: |
          pwd
          cd scripts/
          ls -la
          ./reformat-all-commands.sh ../../../go-algorand/ ../../../indexer/
          git diff
      - name: Create PR
        run: echo "Time to create a PR!"
