name: "Check for go-algorand and indexer releases"
on:
  # schedule:
  #   - cron: '*/30 * * * *'
  push: # For testing only
  workflow_dispatch: # For testing only

jobs:
  release-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs repo
        uses: actions/checkout@v3
        with:
          path: docs

      - name: Clone go-algorand repo
        uses: actions/checkout@v3
        with:
          repository: algorand/go-algorand
          ref: rel/stable
          path: go-algorand

      - name: Clone Indexer repo
        uses: actions/checkout@v3
        with:
          repository: algorand/indexer
          ref: master
          path: indexer

      - name: Get current documentation versions
        run: |
          cd docs
          echo "CURRENT_STABLE_GO_ALGORAND_VERSION=$(cat .go-algorand-stable.version)" >> $GITHUB_ENV
          echo "CURRENT_BETA_GO_ALGORAND_VERSION=$(cat .go-algorand-beta.version)" >> $GITHUB_ENV
          echo "CURRENT_INDEXER_VERSION=$(cat .indexer.version)" >> $GITHUB_ENV

      - name: Get latest stable and beta go-algorand releases
        run: |
          cd go-algorand
          git fetch --tags
          echo "LATEST_STABLE_GO_ALGORAND_RELEASE=$(git tag --list 'v[0-9]*.[0-9]*.[0-9]*-stable' | sort -V | tail -1)" >> $GITHUB_ENV
          echo "LATEST_BETA_GO_ALGORAND_RELEASE=$(git tag --list 'v[0-9]*.[0-9]*.[0-9]*-beta' | sort -V | tail -1)" >> $GITHUB_ENV

      - name: Get latest indexer release without dashes
        run: |
          cd indexer
          git fetch --tags
          echo "LATEST_INDEXER_RELEASE=$(git tag --list '[0-9]*.[0-9]*.[0-9]*' | grep -v '-' | sort -V | tail -1)" >> $GITHUB_ENV

      - name: Trigger docs and version updates if STABLE versions don't match
        if: |
          env.CURRENT_GO_ALGORAND_VERSION != env.LATEST_STABLE_GO_ALGORAND_RELEASE ||
          env.CURRENT_INDEXER_VERSION != env.LATEST_INDEXER_RELEASE
        uses: ./docs/.github/workflows/pr-generator.yml
        with:
          go_algorand_version: ${{ env.LATEST_STABLE_GO_ALGORAND_RELEASE }}
          indexer_version: ${{ env.LATEST_INDEXER_RELEASE }}

      - name: Trigger docs and version updates if BETA versions don't match
        if: |
          env.CURRENT_GO_ALGORAND_VERSION != env.LATEST_BETA_GO_ALGORAND_RELEASE
        uses: ./docs/.github/workflows/pr-generator.yml
        with:
          go_algorand_version: ${{ env.LATEST_BETA_GO_ALGORAND_RELEASE }}
          indexer_version: ${{ env.LATEST_INDEXER_RELEASE }}
