name: "Version Updater"
on:
  workflow_dispatch:
    inputs:
      go_algorand_version:
        description: "Go-Algorand Version"
        type: string
        required: true
  push: # For testing

jobs:
  version-updater:
    runs-on: ubuntu-latest
    steps:

      - name: Clone docs repo
        uses: actions/checkout@v3

      - name: Change version for Beta release
        if: contains(inputs.go_algorand_version, '-beta')
        run: |
          cd docs/get-details/algorand-networks
          sed -i.bak 's/v.*-beta/${{ inputs.go_algorand_version }}/' betanet.md
          rm betanet.md.bak

      - name: Change version for Stable release
        if: contains(inputs.go_algorand_version, '-stable')
        run: |
          cd docs/get-details/algorand-networks
          sed -i.bak 's/v.*-stable/${{ inputs.go_algorand_version }}/' testnet.md
          sed -i.bak 's/v.*-stable/${{ inputs.go_algorand_version }}/' mainnet.md
          rm testnet.md.bak mainnet.md.bak

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: "version-updater-go-algorand-${{ inputs.go_algorand_version }}"
          title: "TEST-DO-NOT-MERGE Automatic PR for new go-algorand version: ${{ inputs.go_algorand_version }}"
          body: "Changes generated by version-updater GitHub Action automatically."
          reviewers: "ejbaran,nullun,barnjamin,ryanrfox"
          delete-branch: true
          base: staging
